app:
  token:
    secret: 5mF9pmpj3pyveaVWdSqvSJml8JAqsR7S0mjOSrqi5LoPqeDqjh+JAxg9zfLu3dhv
    issuer: http://localhost:8080
  activation:
    email:
      maxActivationEmailAttempts: 3
      maxFailedCodeEnteringAttempts: 3
  reset:
    password:
      maxResetPasswordAttempts: 3
      maxFailedCodeEnteringAttempts: 3

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pototsky.ilya212@gmail.com
    password: zgfq npvw rmkv nuoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: patyforboost
  datasource:
    url: jdbc:postgresql://localhost:5432/patyforboost
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml